### ISSUE TITLE
Why this check in cancel_reservation?

### ISSUE THREAD

**Issue by jbrucker** [WorldClassProgrammers/Government-APIs#29]
https://github.com/WorldClassProgrammers/Government-APIs/blob/b6ea0e4c4dec9a79ad8faa517df183c8b2eb0d6b/app/app.py#L522-L524

Suppose someone wants to cancel a reservation and he actually
**does** have a reservation in your database.  Normally this implies
he must be "registered", but even if he is not registered, why not
let him cancel the reservation?

In case the registration database is screwed up or has a bug,
a person should still be able to cancel an appointment.

**Comment by GifperTC** [comment]
The case is very specific and we really appreciate for your suggestions but we have discussed and decided to leave it as it is because we've implement jwt to the cancellation method to prevent direct API DELETE reservation call without authorization.
